version: '3'

services:
  database:
    image: 'mysql:8.0'
    volumes:
      - sfapi:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sfapi
    ports:
      - '3306:3306'
  pma:
    depends_on:
      - database
    image: phpmyadmin:5
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root

volumes:
  sfapi:
